In [93]:
import numpy as np
import pandas as pd

In [94]:
bodyType = pd.read_csv("BodyType.csv")
Enrichment = pd.read_csv("DataEnrichment.csv")

In [95]:
Enrichment.head()

,cylinders,fuel_efficiency_l_per_100km,country_of_origin,Make,Model,fuel_type
0,4.0,8.7,United States,Lincoln,Corsair,Gas
1,4.0,7.6,United States,Jeep,Cherokee,Gas/Electric Hybrid
2,4.0,9.4,South Korea,Hyundai,Tucson,Gas
3,4.0,8.1,Japan,Mazda,CX-5,Gas
4,6.0,11.2,United States,Ford,F-150,Gas

In [96]:
bodyType.head()

      body_type     Make     Model MoreInformation
0           SUV  Lincoln   Corsair             NaN
1           SUV     Jeep  Cherokee             NaN
2           SUV  Hyundai    Tucson             NaN
3           SUV    Mazda      CX-5             NaN
4  Pickup Truck     Ford     F-150             NaN

In [97]:
bodyType["Make_Model"]=(bodyType["Make"]+" " + bodyType["Model"]+" " + bodyType["MoreInformation"].fillna("")).str.split()
bodyType["Quality Check"] =(bodyType["Make"]+" " + bodyType["Model"]+" " + bodyType["MoreInformation"].fillna("")).str.split()

In [98]:
bodyType["Make_Model"] = bodyType["Make_Model"].apply(lambda x: " ".join(x) if isinstance(x, list) else x)
bodyType["Quality Check"] = bodyType["Quality Check"].apply(lambda x: " ".join(x) if isinstance(x, list) else x)

In [99]:
Enrichment["Make_Model"]=Enrichment["Make"] + " " + Enrichment["Model"]

In [ ]:
df=Enrichment.merge(bodyType,on=["Make_Model"],how="left")
df.to_csv("MainDataEnrichement.csv")